FileVersion = 1

[Project]
Name = "tinyregexc-beef"
DefaultNamespace = "tinyregexc"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\debug\\tinyregexc.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\tinyregexc.lib"]
