FileVersion = 1

[Project]
Name = "tinyregexc-beef"
DefaultNamespace = "tinyregexc"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\tinyregexc_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\tinyregexc.lib"]
